apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  PORT: "3000"
  HOST: "0.0.0.0"
  AUTH_SERVICE_URL: "http://auth-service:8001"
  AI_SERVICE_URL: "http://ai-service:8000"
  HR_SERVICE_URL: "http://hr-service:8002"
  FINANCE_SERVICE_URL: "http://finance-service:8004"
  PROJECT_SERVICE_URL: "http://project-service:8003"
