apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  # Internal URLs mapping to K8s Service Names
  AUTH_SERVICE_URL: "http://auth-service:8001"
  AI_SERVICE_URL: "http://ai-service:8000"
  HR_SERVICE_URL: "http://hr-service:8002"
  PROJECT_SERVICE_URL: "http://project-service:8003"
  FINANCE_SERVICE_URL: "http://finance-service:8004"
