# Global values shared across all subcharts
global:
  azure:
    tenantId: "YOUR_TENANT_ID"
    keyvaultName: "Mahesh-KeyV"
    storageAccountName: "maheshstoracc"
    identityClientId: "YOUR_USER_ASSIGNED_IDENTITY_CLIENT_ID"
    # Container Registry
    registryServer: "organistationacr.azurecr.io"
  
  # Environment (production | staging | dev)
  env: production

  # Common DB configuration
  cosmos:
    dbNameSuffix: "_prod"
    # Connection string is usually pulled from Vault, but can be set here for dev
    connectionString: ""

# Individual Subchart Overrides
auth-service:
  enabled: true
  replicaCount: 2
  image:
    repository: organistation-auth
    tag: v1.0.0

ai-service:
  enabled: true
  replicaCount: 1
  image:
    repository: organistation-ai
    tag: v1.0.0
  storage:
    containerName: "organistation-docs"

hr-service:
  enabled: true
  replicaCount: 1
  image:
    repository: organistation-hr
    tag: v1.0.0

finance-service:
  enabled: true
  replicaCount: 1
  image:
    repository: organistation-finance
    tag: v1.0.0

project-service:
  enabled: true
  replicaCount: 1
  image:
    repository: organistation-projects
    tag: v1.0.0

gateway-service:
  enabled: true
  replicaCount: 2
  image:
    repository: organistation-gateway
    tag: v1.0.0
  service:
    type: LoadBalancer # For public access
    port: 80
