name: hr-service
replicaCount: 1
rollingUpdate: { type: RollingUpdate, maxUnavailable: 0, maxSurge: 1 }
image: { name: maheshnandi/organistation-hr, tag: latest, pullPolicy: IfNotPresent }
service: { port: 8002, targetPort: 8002 }
resources:
  limits: { cpu: 500m, memory: 512Mi }
  requests: { cpu: 100m, memory: 256Mi }
