apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: organization-vault-provider
spec:
  provider: azure

  parameters:
    keyvaultName: {{ .Values.global.azure.keyvaultName | quote }}
    tenantId: {{ .Values.global.azure.tenantId | quote }}
    clientID: {{ .Values.global.azure.identityClientId | quote }}

    usePodIdentity: "false"
    useVMManagedIdentity: "false"

    objects: |
      array:
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: internal-secret
          objectType: secret
        - |
          objectName: storage-key
          objectType: secret
        - |
          objectName: groq-api-key
          objectType: secret
        - |
          objectName: cosmos-connection-string
          objectType: secret

  secretObjects:
    - secretName: auth-service-secret
      type: Opaque
      data:
        - objectName: jwt-secret
          key: JWT_SECRET
        - objectName: internal-secret
          key: INTERNAL_SERVICE_SECRET
        - objectName: cosmos-connection-string
          key: COSMOS_CONNECTION_STRING