apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: organization-vault-provider
spec:
  provider: azure
  secretObjects:
    # Auth Service Secret
    - secretName: auth-service-secret
      type: Opaque
      data:
        - objectName: jwt-secret
          key: JWT_SECRET
        - objectName: internal-secret
          key: INTERNAL_SERVICE_SECRET
        - objectName: cosmos-connection-string
          key: COSMOS_CONNECTION_STRING
    
    # AI Service Secret
    - secretName: ai-service-secret
      type: Opaque
      data:
        - objectName: storage-key
          key: STORAGE_ACCOUNT_KEY
        - objectName: groq-api-key
          key: GROQ_API_KEY
    
    # Gateway Secret
    - secretName: gateway-service-secret
      type: Opaque
      data:
        - objectName: jwt-secret
          key: JWT_SECRET

    # HR, Projects, Finance Secrets
    - secretName: hr-service-secret
      type: Opaque
      data:
        - objectName: internal-secret
          key: INTERNAL_SERVICE_SECRET
        - objectName: cosmos-connection-string
          key: COSMOS_CONNECTION_STRING
    - secretName: finance-service-secret
      type: Opaque
      data:
        - objectName: internal-secret
          key: INTERNAL_SERVICE_SECRET
        - objectName: cosmos-connection-string
          key: COSMOS_CONNECTION_STRING
    - secretName: project-service-secret
      type: Opaque
      data:
        - objectName: internal-secret
          key: INTERNAL_SERVICE_SECRET
        - objectName: cosmos-connection-string
          key: COSMOS_CONNECTION_STRING

  parameters:
    useWorkloadIdentity: "true"
    userAssignedIdentityID: {{ .Values.global.azure.identityClientId | quote }}
    keyvaultName: {{ .Values.global.azure.keyvaultName | quote }}
    objects: |
      array:
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: internal-secret
          objectType: secret
        - |
          objectName: storage-key
          objectType: secret
        - |
          objectName: groq-api-key
          objectType: secret
        - |
          objectName: cosmos-connection-string
          objectType: secret
    tenantId: {{ .Values.global.azure.tenantId | quote }}
