apiVersion: v1
kind: ServiceAccount
metadata:
  name: organistation-sa
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.azure.identityClientId | quote }}
  labels:
    azure.workload.identity/use: "true"
